update main page
PowerGridModel/power-grid-model pull request #342
Opened 2023-08-08 13:21 UTC by nitbharambe

2023-08-08 13:22 UTC, mgovers submitted a review, later dismissed

2023-08-08 13:29 UTC, mgovers requested changes

2023-08-08 13:29 UTC, mgovers commented on docs/index.md
> +* Short circuit
inconsistent capitalizing. please use either

```suggestion
* Power Flow
* State Estimation
* Short Circuit
```

or

```suggestion
* Power flow
* State estimation
* Short circuit
```

or

```suggestion
* power flow
* state estimation
* short circuit
```

2023-08-08 14:24 UTC, mgovers commented on docs/index.md
> +* Short Circuit
now it's inconsistent 😉 
```suggestion
* Power flow
* State estimation
* Short circuit
```

2023-08-09 09:25 UTC, TonyXiang8787 approved these changes

2023-08-09 11:19 UTC, merged