fix links in examples
PowerGridModel/power-grid-model pull request #401
Opened 2023-10-10 13:56 UTC by Laurynas-Jagutis

Updated the links in the example notebooks.

2023-10-10 14:42 UTC, mgovers requested changes
this PR should be very small and only change the sections references. all the rest should be automated in the workshop repo and readthedocs (the later already should be correct)

2023-10-10 14:42 UTC, mgovers commented on docs/examples/Make Test Dataset.ipynb
> +    "[Serialization documentation](https://power-grid-model.readthedocs.io/en/stable/user_manual/serialization.html#serialization) and some examples of Serialization are given in [Serialization noteb
please revert this. you will need to automate adding the `https://power-grid-model.readthedocs.io/en/stable` prefix and making `md` => `html` in the workshop repo

2023-10-10 14:42 UTC, mgovers commented on docs/examples/Make Test Dataset.ipynb
> +   "version": "3.9.13"
please don't downgrade python this much. instead, either undo this change, or make sure you have the latest python 3.11 installed and then rerun the examples using your version (preferably not in this PR though)

2023-10-10 14:42 UTC, mgovers commented on docs/examples/Power Flow Example.ipynb
> +    "and [Native Data Interface](https://power-grid-model.readthedocs.io/en/stable/advanced_documentation/native-data-interface.html#native-data-interface).\n",
as before: the relative links were OK

2023-10-10 14:42 UTC, mgovers commented on docs/examples/Power Flow Example.ipynb
> +    "Please refer to [Components](https://power-grid-model.readthedocs.io/en/stable/user_manual/components.html#components) for detailed explanation of all component types and their input/output attr
as before: the relative links were OK

2023-10-10 14:42 UTC, mgovers commented on docs/examples/Power Flow Example.ipynb
> +    "See also [performance guide](https://power-grid-model.readthedocs.io/en/stable/user_manual/performance-guide.html#guidelines-for-performance-enhancement) for the latest recommendations."
as before: the relative links were OK

2023-10-10 14:42 UTC, mgovers commented on docs/examples/Serialization Example.ipynb
> +   "version": "3.9.13"
as before: don't downgrade Python

2023-10-10 14:42 UTC, mgovers commented on docs/examples/Short Circuit Example.ipynb
> +    "and [Native Data Interface](https://power-grid-model.readthedocs.io/en/stable/advanced_documentation/native-data-interface.html#native-data-interface).\n",
as before: the relative links were OK

2023-10-10 14:42 UTC, mgovers commented on docs/examples/Short Circuit Example.ipynb
> +    "Please refer to [Components](https://power-grid-model.readthedocs.io/en/stable/user_manual/components.html#components) for detailed explanation of all component types and their input/output attr
as before: the relative links were OK

2023-10-10 14:42 UTC, mgovers commented on docs/examples/State Estimation Example.ipynb
> +    "and [Native Data Interface](https://power-grid-model.readthedocs.io/en/stable/advanced_documentation/native-data-interface.html#native-data-interface).\n",
as before: the relative links were OK

2023-10-10 14:42 UTC, mgovers commented on docs/examples/State Estimation Example.ipynb
> +    "Please refer [Components](https://power-grid-model.readthedocs.io/en/stable/user_manual/components.html#components) for detailed explanation of all component types and their input/output attribu
as before: the relative links were OK

2023-10-10 14:42 UTC, mgovers commented on docs/examples/State Estimation Example.ipynb
> +    "For state estimation a batch calculation can be performed in a similar manner as for powerflow calculations. Below is a short example provided for reference. For more a more detailed example abo
as before: the relative links were OK

2023-10-11 13:26 UTC, TonyXiang8787 commented
@mgovers why do we need this? The relative links work just fine.

2023-10-11 13:29 UTC, mgovers commented
> @mgovers why do we need this? The relative links work just fine.

yes i agree. see also my list of comments.

@Laurynas-Jagutis found a small bug where 3 links referred specifically to the `#utils` subsection of the python documentation, and we agreed to fix only those 3 links, but then this PR became much bigger.

I believe the reason is to fix the links in the workshop repo (those should point to the PGM docs, not to relative paths). But those link edits should live in the automation in the workshop repo - not here.

2023-10-12 11:55 UTC, mgovers approved these changes

2023-10-12 13:37 UTC, merged