Feature/sustainable solution for bug
PowerGridModel/power-grid-model pull request #468
Opened 2024-01-15 11:50 UTC by mgovers

Sustainable solution for #461 .
Replaces quick fix in #462 .
Tests in #460 .

A large portion of the complexity in the batch update is refactored away to separate lambda functions:

* The construction of the sub batch calculation is moved to a separate function, as well as its dispatching
* Each scenario itself has a separate setup, winddown and run and also has an exception handler and a recovery method for otherwise unfixable errors
* the Lippincott pattern is used to handle all scenario exceptions in one go https://en.cppreference.com/w/cpp/error/current_exception . That way, the actual implementation for the running of the scenario only requires one try/catch block

2024-01-15 13:14 UTC, TonyXiang8787 commented
should this be merged before #460?

2024-01-16 09:01 UTC, TonyXiang8787 commented
@mgovers If this is still working in progress, please put the PR in draft.

2024-01-16 09:15 UTC, mgovers commented
> @mgovers If this is still working in progress, please put the PR in draft.

everything is done except for sonar cloud/CI. i thought it was already ready for review until i saw the code smells. CI should pass now. If not, i'll pull it back to draft

2024-01-16 09:29 UTC, mgovers commented
remaining code smells were already introduced in original `main` but just were moved around

2024-01-16 09:44 UTC, TonyXiang8787 requested changes
We were using some confusing names before. Since we are refactoring here, please change the names of variables correctly using the terminology defined here.

https://power-grid-model.readthedocs.io/en/stable/user_manual/dataset-terminology.html

Especially, we use the loop variable name `batch_number` , it should be actually `scenario_number`. We only have one batch, which consists of multiple sub-batches for multithreading, which consist again multiple scenarios per sub-batch.

2024-01-16 09:55 UTC, TonyXiang8787 approved these changes

2024-01-16 10:49 UTC, merged